# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WilddogLocationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WilddogLocationDemo

  pod 'WilddogLocation'
  pod 'AMap3DMap'

  target 'WilddogLocationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WilddogLocationDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
